# global params
random state: 42
data path: 
save path: 

# train params
choose model: xgboost.XGBRegressor
descriptor type: oliynyk
threshold: 0.75
test set: 0.1
cv: 10

# optim params
search type: bayes
scoring: r2
save log: True
log path: 
epoch: 5
init_points: 10
n_iter: 40
parameters space: 
  n_estimators: 
    list: False
    type: int
    start: 1
    end: 1000
    step: 
  learning_rate: 
    list: False
    type: float
    start: 0.01
    end: 0.5
    step: 
  max_depth: 
    list: False
    type: int
    start: 1
    end: 50
    step: 